# -*- coding: utf-8 -*-
"""Workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsiBHyUWIKCZcYf_3juDw0_jKCdlesyf
"""

# TASK 1: Read + Display

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# 🔁 Change this to your uploaded image file name
filename = "image.jpg"

# Read image using Pillow
img = Image.open(filename)

# Convert to NumPy array
img_array = np.array(img)

# Display original image
plt.imshow(img_array)
plt.title(" Original Image")
plt.axis("off")
plt.show()

print("Image shape:", img_array.shape)  # should be (H, W, 3) for RGB

# TASK 2: Top-left 100x100

top_left = img_array[0:100, 0:100]   # rows 0-99, cols 0-99

plt.imshow(top_left)
plt.title("Top-left 100x100")
plt.axis("off")
plt.show()

# TASK 3: Show RGB channels

R = img_array[:, :, 0]   # Red channel
G = img_array[:, :, 1]   # Green channel
B = img_array[:, :, 2]   # Blue channel

plt.imshow(R, cmap="Reds")
plt.title("R (Red Channel)")
plt.axis("off")
plt.show()

plt.imshow(G, cmap="Greens")
plt.title(" G (Green Channel)")
plt.axis("off")
plt.show()

plt.imshow(B, cmap="Blues")
plt.title(" B (Blue Channel)")
plt.axis("off")
plt.show()

# TASK 4: Modify top 100x100 to 210

modified = img_array.copy()

# Set top-left 100x100 region to 210 (light gray)
modified[0:100, 0:100] = 210

plt.imshow(modified)
plt.title("Modified Image (Top-left 100x100 = 210)")
plt.axis("off")
plt.show()

#2 task1
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# 🔁 Change this to your uploaded file name
filename = "image.jpg"

# 1) Load image as GRAYSCALE
img_gray = Image.open(filename).convert("L")   # "L" = grayscale
gray_array = np.array(img_gray)

# Display grayscale image
plt.imshow(gray_array, cmap="gray")
plt.title(" Grayscale Image")
plt.axis("off")
plt.show()

print("Grayscale shape:", gray_array.shape)  # should be (H, W)

#task2
H, W = gray_array.shape

crop_size = 150
start_row = (H - crop_size) // 2
start_col = (W - crop_size) // 2

middle_150 = gray_array[start_row:start_row+crop_size, start_col:start_col+crop_size]

plt.imshow(middle_150, cmap="gray")
plt.title(" Middle 150x150 Section")
plt.axis("off")
plt.show()

#task3
binary = np.where(gray_array < 100, 0, 255).astype(np.uint8)

plt.imshow(binary, cmap="gray")
plt.title("Thresholded Binary Image")
plt.axis("off")
plt.show()

rotated_clockwise = np.rot90(gray_array, k=-1)  # k=-1 means 90° clockwise

plt.imshow(rotated_clockwise, cmap="gray")
plt.title("Rotated 90° Clockwise")
plt.axis("off")
plt.show()

rgb_array = np.stack([gray_array, gray_array, gray_array], axis=-1)  # shape (H, W, 3)

plt.imshow(rgb_array)
plt.title(" Grayscale Converted to RGB")
plt.axis("off")
plt.show()

print("RGB shape:", rgb_array.shape)  # should be (H, W, 3)

#3