# -*- coding: utf-8 -*-
"""Worksheet0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAdXO41aw22XWuzpsh0xCAduV-UcHLTz
"""

#task1
def unit_converter(conversion_type, value, direction):
    """
    Converts units of measurement between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion ('length', 'weight', 'volume')
    value (float): Numeric value to convert
    direction (str): Conversion direction

    Returns:
    float: Converted value
    """

    if conversion_type == "length":
        if direction == "m_to_ft":
            return value * 3.28084
        elif direction == "ft_to_m":
            return value / 3.28084

    elif conversion_type == "weight":
        if direction == "kg_to_lbs":
            return value * 2.20462
        elif direction == "lbs_to_kg":
            return value / 2.20462

    elif conversion_type == "volume":
        if direction == "l_to_gal":
            return value * 0.264172
        elif direction == "gal_to_l":
            return value / 0.264172

    else:
        raise ValueError("Unsupported conversion type.")


# Main Program
try:
    ctype = input("Enter conversion type (length/weight/volume): ").lower()
    val = float(input("Enter value to convert: "))
    direction = input("Enter direction (example: m_to_ft): ").lower()

    result = unit_converter(ctype, val, direction)
    print("Converted Value:", result)

except ValueError as e:
    print("Error:", e)
except Exception:
    print("Invalid input provided.")

def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def calculate_max(numbers):
    """Returns the maximum value in a list."""
    return max(numbers)

def calculate_min(numbers):
    """Returns the minimum value in a list."""
    return min(numbers)


try:
    operation = input("Choose operation (sum/avg/max/min): ").lower()
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    if not nums:
        raise ValueError("List cannot be empty.")

    if operation == "sum":
        print("Result:", calculate_sum(nums))
    elif operation == "avg":
        print("Result:", calculate_average(nums))
    elif operation == "max":
        print("Result:", calculate_max(nums))
    elif operation == "min":
        print("Result:", calculate_min(nums))
    else:
        print("Invalid operation.")

except ValueError as e:
    print("Error:", e)

def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[:n]

def get_last_n(lst, n):
    return lst[-n:]

def reverse_skip(lst):
    return lst[-2::-2]


lst = [1,2,3,4,5,6]

print("Original list:", lst)

print("Every other element:", extract_every_other(lst))

print("Sublist (2 to 4):", get_sublist(lst,2,4))

print("Reversed list:", reverse_list(lst))

print("Remove first and last:", remove_first_last(lst))

print("First 3 elements:", get_first_n(lst,3))

print("Last 2 elements:", get_last_n(lst,2))

print("Reverse skip:", reverse_skip(lst))

def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    result = lst
    for index in indices:
        result = result[index]
    return result

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        elif item != elem:
            new_list.append(item)
    return new_list

def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    return flatten(lst)

def average_nested(lst):
    flat = flatten(lst)
    return sum(flat) / len(flat)